### ISSUE TITLE
Doesn't work without deps in python 2 ... python 3 libs used but syntax incorrect?

### ISSUE THREAD

**Issue by untoldone** [nopejpg/check-es#2]
~# /srv/consul/check_es.py
Traceback (most recent call last):
  File "/srv/consul/check_es.py", line 35, in <module>
    import ipaddress
ImportError: No module named ipaddress

~# python3 /srv/consul/check_es.py
  File "/srv/consul/check_es.py", line 259
    except Exception, e:
                    ^
SyntaxError: invalid syntax

**Comment by nopejpg** [comment]
Should be resolved

**Comment by nopejpg** [comment]
Closing
